//
// webui_assets.h
//
// Table of static web UI assets embedded in the kernel image.
// The .c counterpart is generated by tools/gen_webui_assets.py.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef _webui_assets_h
#define _webui_assets_h

#ifdef __cplusplus
extern "C" {
#endif

struct webui_asset {
  const char *path;          // request path, e.g. "/" or "/app.js"
  const char *content_type;  // value for the Content-Type header
  const unsigned char *data; // asset bytes (not NUL terminated)
  unsigned int length;       // number of bytes
};

extern const struct webui_asset g_webui_assets[];
extern const unsigned int g_webui_asset_count;

#ifdef __cplusplus
}
#endif

#endif
